### PR TITLE
Remove uniqueness constraint from org name

### LINKED ISSUE #104: New lines with matching fields will fail
Take the case of two CSVS:

**A**
```
organization_name,website,location,phone_number,email
"Foo's Bar", example.com, "Detroit, MI", , 
```

**B**
```
organization_name,website,location,phone_number,email
"Foo's Bar", example.com, , , foosbar@example.com
```

Both imports `A` and `B` are equally important. Unfortunately, `B` will fail because the row's import is saved in a transaction and `Foo's Bar` is invalid, since it already exists.

See https://github.com/artsy/bearden/pull/117 for a failing test.

### PR DESCRIPTION
**Pull request by jonallured**
Rather than have this Rankable behave differently than the others, we've
decided that it should rely on Source rank resolution too.

closes #104

### CODE REVIEW

File: app/models/organization_name.rb [hunk 1]
```diff
@@ -2,7 +2,6 @@ class OrganizationName < ApplicationRecord
   belongs_to :organization
 
   validates :content, presence: true
-  validates_uniqueness_of :content, scope: :organization
```
Comment (gnilekaw) [inline app/models/organization_name.rb]: 👋
